load("//rules:eac.bzl", "cfg6_eac_argument")

package(default_visibility = ["//visibility:public"])

filegroup(
    name = "srcs",
    srcs = glob(["**"]),
    visibility = ["//build:package_group"],
)

cfg6_eac_argument(
    name = "false",
    value = "false",
)

cfg6_eac_argument(
    name = "true",
    value = "true",
)
